### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'

### ISSUE THREAD

**Issue by ishandutta2007** [shiburagi/Messaging-App#2]
The app is not building, I updated all build tools as per whatever android studio suggested
```
Error:Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.app.infideap.readcontact'
```

**Comment by shiburagi** [comment]
did u already create firebase project?
please refer to readme how to configure it

**Comment by shiburagi** [comment]
https://github.com/shiburagi/Messaging-App/blob/dev_shiburagi/README.md

**Comment by shiburagi** [comment]
Hi,
I already add radius effect in drawer library.

*How to Use:*

   1. upgrade library to 0.0.2, *compile
   'com.infideap.drawerbehavior:drawer-behavior:0.0.2'*
   2. use this *method* to implement *cardview* radius *effect*,*
   drawer.setRadius(Gravity.START, 25)*

for more info,
https://github.com/shiburagi/Drawer-Behavior/blob/master/README.md
